#!/usr/bin/env python
import carrier.server
import bottle
import sys

def main():
    bottle.run(app=carrier.server.application, host='0.0.0.0', port=3000)

if __name__ == '__main__':
    sys.exit(main())
